=== commercetools/merchant-center-application-kit/packages/application-config/custom-application.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://docs.commercetools.com/merchant-center-customizations/custom-application.schema.json",
  "title": "JSON schema for Custom Application configuration files",
  "type": "object",
  "definitions": {
    "cspDirective": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    }
  },
  "properties": {
    "name": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#name",
      "type": "string"
    },
    "description": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#description",
      "type": "string"
    },
    "entryPointUriPath": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#entrypointuripath",
      "type": "string"
    },
    "cloudIdentifier": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#cloudidentifier",
      "type": "string"
    },
    "mcApiUrl": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#mcapiurl",
      "type": "string"
    },
    "oAuthScopes": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#oauthscopes",
      "type": "object",
      "properties": {
        "view": {
          "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#oauthscopesview",
          "type": "array",
          "default": [],
          "items": {
            "type": "string",
            "pattern": "view_(.*)"
          },
          "uniqueItems": true
        },
        "manage": {
          "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#oauthscopesmanage",
          "type": "array",
          "default": [],
          "items": {
            "type": "string",
            "pattern": "manage_(.*)"
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false,
      "required": ["view", "manage"]
    },
    "additionalOAuthScopes": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#additionaloauthscopes",
      "type": "array",
      "default": [],
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#additionaloauthscopesname",
            "type": "string"
          },
          "view": {
            "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#additionaloauthscopesview",
            "type": "array",
            "default": [],
            "items": {
              "type": "string",
              "pattern": "view_(.*)"
            },
            "uniqueItems": true
          },
          "manage": {
            "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#additionaloauthscopesmanage",
            "type": "array",
            "default": [],
            "items": {
              "type": "string",
              "pattern": "manage_(.*)"
            },
            "uniqueItems": true
          }
        },
        "additionalProperties": false,
        "required": ["name", "view", "manage"]
      }
    },
    "env": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#env",
      "type": "object",
      "properties": {
        "development": {
          "type": "object",
          "properties": {
            "initialProjectKey": {
              "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#envdevelopmentinitialprojectkey",
              "type": "string"
            },
            "teamId": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": ["initialProjectKey"]
        },
        "production": {
          "type": "object",
          "properties": {
            "applicationId": {
              "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#envproductionapplicationid",
              "type": "string"
            },
            "url": {
              "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#envproductionurl",
              "type": "string"
            },
            "cdnUrl": {
              "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#envproductioncdnurl",
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": ["applicationId", "url"]
        }
      },
      "additionalProperties": false,
      "required": ["development", "production"]
    },
    "additionalEnv": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#additionalenv",
      "type": "object"
    },
    "headers": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#headers",
      "type": "object",
      "properties": {
        "csp": {
          "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#headerscsp",
          "type": "object",
          "properties": {
            "connect-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "font-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "img-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "script-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "style-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "frame-src": {
              "$ref": "#/definitions/cspDirective"
            }
          },
          "additionalProperties": false,
          "required": ["connect-src"]
        },
        "permissionsPolicies": {
          "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#headerspermissionspolicies",
          "type": "object"
        },
        "strictTransportSecurity": {
          "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#headersstricttransportsecurity",
          "type": "array",
          "items": {
            "enum": ["includeSubDomains", "preload"]
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false
    },
    "icon": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#icon",
      "type": "string"
    },
    "mainMenuLink": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#mainmenulink",
      "type": "object",
      "properties": {
        "defaultLabel": {
          "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#mainmenulinkdefaultlabel",
          "type": "string"
        },
        "labelAllLocales": {
          "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#mainmenulinklabelalllocales",
          "type": "array",
          "default": [],
          "items": {
            "type": "object",
            "properties": {
              "locale": {
                "type": "string",
                "enum": ["en", "de", "es", "fr-FR", "pt-BR", "zh-CN"]
              },
              "value": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": ["locale", "value"]
          }
        },
        "permissions": {
          "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#mainmenulinkpermissions",
          "type": "array",
          "default": [],
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": true,
      "required": ["defaultLabel", "labelAllLocales", "permissions"]
    },
    "submenuLinks": {
      "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#submenulinks",
      "default": [],
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uriPath": {
            "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#submenulinksuripath",
            "type": "string"
          },
          "defaultLabel": {
            "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#submenulinksdefaultlabel",
            "type": "string"
          },
          "labelAllLocales": {
            "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#submenulinkslabelalllocales",
            "type": "array",
            "default": [],
            "items": {
              "type": "object",
              "properties": {
                "locale": {
                  "type": "string",
                  "enum": ["en", "de", "es", "fr-FR", "pt-BR", "zh-CN"]
                },
                "value": {
                  "type": "string"
                }
              },
              "additionalProperties": false,
              "required": ["locale", "value"]
            }
          },
          "permissions": {
            "description": "See https://docs.commercetools.com/merchant-center-customizations/api-reference/custom-application-config#submenulinkspermissions",
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          }
        },
        "additionalProperties": true,
        "required": [
          "uriPath",
          "defaultLabel",
          "labelAllLocales",
          "permissions"
        ]
      }
    }
  },
  "additionalProperties": true,
  "required": [
    "name",
    "entryPointUriPath",
    "cloudIdentifier",
    "env",
    "oAuthScopes",
    "icon",
    "mainMenuLink",
    "submenuLinks"
  ]
}

=== commercetools/merchant-center-application-kit/packages/application-config/test/fixtures/config-oidc.json
{
  "name": "avengers-app",
  "entryPointUriPath": "avengers",
  "cloudIdentifier": "gcp-eu",
  "env": {
    "development": {
      "initialProjectKey": "project-key"
    },
    "production": {
      "applicationId": "app-id-123",
      "url": "https://avengers.app"
    }
  },
  "oAuthScopes": {
    "view": ["view_orders", "view_states"],
    "manage": ["manage_orders"]
  },
  "icon": "<svg><path fill=\"#000000\" /></svg>",
  "mainMenuLink": {
    "defaultLabel": "Avengers",
    "labelAllLocales": [],
    "permissions": []
  },
  "submenuLinks": []
}

=== commercetools/merchant-center-application-kit/packages/application-config/test/fixtures/config-file-path-variables.json
{
  "name": "avengers-app",
  "entryPointUriPath": "avengers",
  "cloudIdentifier": "gcp-eu",
  "env": {
    "development": {
      "initialProjectKey": "test"
    },
    "production": {
      "applicationId": "app-id-123",
      "url": "https://my-app.com"
    }
  },
  "oAuthScopes": {
    "view": ["view_products"],
    "manage": []
  },
  "icon": "${path:@commercetools-frontend/assets/application-icons/rocket.svg}",
  "mainMenuLink": {
    "defaultLabel": "Avengers",
    "labelAllLocales": [
      {
        "locale": "en",
        "value": "${intl:en:Menu.Avengers}"
      }
    ],
    "permissions": ["ViewAvengers"]
  },
  "submenuLinks": []
}

=== commercetools/merchant-center-application-kit/packages/application-config/test/fixtures/custom-applications/config-full.json
{
  "name": "avengers-app",
  "cloudIdentifier": "gcp-eu",
  "entryPointUriPath": "avengers",
  "env": {
    "development": {
      "initialProjectKey": "test"
    },
    "production": {
      "applicationId": "app-id-123",
      "url": "https://avengers.app",
      "cdnUrl": "https://cdn.avengers.app"
    }
  },
  "additionalEnv": {
    "numberOfMovies": 4,
    "empty": ""
  },
  "oAuthScopes": {
    "view": ["view_products"],
    "manage": []
  },
  "additionalOAuthScopes": [
    {
      "name": "movies",
      "view": ["view_products"],
      "manage": []
    },
    {
      "name": "merch",
      "view": ["view_channels"],
      "manage": ["manage_channels"]
    }
  ],
  "headers": {
    "csp": {
      "script-src": ["https://track.avengers.app"],
      "connect-src": ["https://track.avengers.app"]
    },
    "permissionsPolicies": {
      "microphone": "*"
    }
  },
  "icon": "<svg><path fill=\"#000000\" /></svg>",
  "mainMenuLink": {
    "defaultLabel": "Avengers",
    "labelAllLocales": [],
    "permissions": []
  },
  "submenuLinks": []
}

=== commercetools/merchant-center-application-kit/packages/application-config/test/fixtures/custom-applications/config-oidc.json
{
  "name": "avengers-app",
  "entryPointUriPath": "avengers",
  "cloudIdentifier": "gcp-eu",
  "env": {
    "development": {
      "initialProjectKey": "project-key"
    },
    "production": {
      "applicationId": "app-id-123",
      "url": "https://avengers.app"
    }
  },
  "oAuthScopes": {
    "view": ["view_orders", "view_states"],
    "manage": ["manage_orders"]
  },
  "additionalOAuthScopes": [
    {
      "name": "movies",
      "view": ["view_products"],
      "manage": []
    },
    {
      "name": "merch",
      "view": [],
      "manage": ["manage_channels"]
    }
  ],
  "icon": "<svg><path fill=\"#000000\" /></svg>",
  "mainMenuLink": {
    "defaultLabel": "Avengers",
    "labelAllLocales": [],
    "permissions": []
  },
  "submenuLinks": []
}
