=== commercetools/merchant-center-application-kit/packages/application-config/custom-view.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://docs.commercetools.com/custom-applications/custom-view.schema.json",
  "title": "JSON schema for Custom View configuration files",
  "type": "object",
  "definitions": {
    "cspDirective": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    }
  },
  "properties": {
    "name": {
      "description": "See https://docs.commercetools.com/",
      "type": "string"
    },
    "description": {
      "description": "See https://docs.commercetools.com/",
      "type": "string"
    },
    "cloudIdentifier": {
      "description": "See https://docs.commercetools.com/",
      "type": "string"
    },
    "mcApiUrl": {
      "description": "See https://docs.commercetools.com/",
      "type": "string"
    },
    "oAuthScopes": {
      "description": "See https://docs.commercetools.com/",
      "type": "object",
      "properties": {
        "view": {
          "description": "See https://docs.commercetools.com/",
          "type": "array",
          "default": [],
          "items": {
            "type": "string",
            "pattern": "view_(.*)"
          },
          "uniqueItems": true
        },
        "manage": {
          "description": "See https://docs.commercetools.com/",
          "type": "array",
          "default": [],
          "items": {
            "type": "string",
            "pattern": "manage_(.*)"
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false,
      "required": ["view", "manage"]
    },
    "additionalOAuthScopes": {
      "description": "See https://docs.commercetools.com/",
      "type": "array",
      "default": [],
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "See https://docs.commercetools.com/",
            "type": "string"
          },
          "view": {
            "description": "See https://docs.commercetools.com/",
            "type": "array",
            "default": [],
            "items": {
              "type": "string",
              "pattern": "view_(.*)"
            },
            "uniqueItems": true
          },
          "manage": {
            "description": "See https://docs.commercetools.com/",
            "type": "array",
            "default": [],
            "items": {
              "type": "string",
              "pattern": "manage_(.*)"
            },
            "uniqueItems": true
          }
        },
        "additionalProperties": false,
        "required": ["name", "view", "manage"]
      }
    },
    "env": {
      "description": "See https://docs.commercetools.com/",
      "type": "object",
      "properties": {
        "development": {
          "type": "object",
          "properties": {
            "initialProjectKey": {
              "description": "See https://docs.commercetools.com/",
              "type": "string"
            },
            "teamId": {
              "type": "string"
            },
            "hostUrl": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": ["initialProjectKey"]
        },
        "production": {
          "type": "object",
          "properties": {
            "customViewId": {
              "description": "See https://docs.commercetools.com/",
              "type": "string"
            },
            "url": {
              "description": "See https://docs.commercetools.com/",
              "type": "string"
            },
            "cdnUrl": {
              "description": "See https://docs.commercetools.com/",
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": ["customViewId", "url"]
        }
      },
      "additionalProperties": false,
      "required": ["development", "production"]
    },
    "additionalEnv": {
      "description": "See https://docs.commercetools.com/",
      "type": "object"
    },
    "headers": {
      "description": "See https://docs.commercetools.com/",
      "type": "object",
      "properties": {
        "csp": {
          "description": "See https://docs.commercetools.com/",
          "type": "object",
          "properties": {
            "connect-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "font-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "img-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "script-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "style-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "frame-src": {
              "$ref": "#/definitions/cspDirective"
            }
          },
          "additionalProperties": false,
          "required": ["connect-src"]
        },
        "permissionsPolicies": {
          "description": "See https://docs.commercetools.com/",
          "type": "object"
        },
        "strictTransportSecurity": {
          "description": "See https://docs.commercetools.com/",
          "type": "array",
          "items": {
            "enum": ["includeSubDomains", "preload"]
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false
    },
    "type": {
      "description": "See https://docs.commercetools.com/",
      "type": "string",
      "enum": ["CustomPanel"]
    },
    "typeSettings": {
      "description": "See https://docs.commercetools.com/",
      "type": "object",
      "properties": {
        "size": {
          "description": "See https://docs.commercetools.com/",
          "type": "string",
          "enum": ["SMALL", "LARGE"]
        }
      }
    }
  },
  "additionalProperties": true,
  "required": ["name", "cloudIdentifier", "env", "oAuthScopes", "type"]
}

=== commercetools/merchant-center-application-kit/packages/application-config/test/fixtures/custom-views/config-simple.json
{
  "name": "avengers-custom-view",
  "cloudIdentifier": "gcp-eu",
  "env": {
    "development": {
      "initialProjectKey": "test"
    },
    "production": {
      "customViewId": "custom-view-id-123",
      "url": "https://avengers.app"
    }
  },
  "oAuthScopes": {
    "view": ["view_products"],
    "manage": []
  },
  "type": "CustomPanel",
  "typeSettings": {
    "size": "LARGE"
  }
}
