=== commercetools/merchant-center-application-kit/packages/application-config/schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://unpkg.com/@commercetools-frontend/application-config/schema.json",
  "title": "JSON schema for Custom Application configuration files",
  "type": "object",
  "definitions": {
    "environmentVariable": {
      "type": "string",
      "pattern": "(\\$\\{env:\\w+\\})+"
    },
    "menuLink": {
      "type": "object",
      "properties": {
        "uriPath": {
          "description": "The URI path of the link",
          "type": "string"
        },
        "permissions": {
          "description": "A list of permissions that should be applied to the link",
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        },
        "labelAllLocales": {
          "description": "Translations for the link",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "locale": {
                "description": "The locale for the translation, for example `en`",
                "type": "string",
                "minLength": 2
              },
              "value": {
                "description": "The translation value",
                "type": "string"
              }
            }
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "featureToggle": {
          "description": "The name of a feature toggle (internal use only)",
          "type": "string",
          "default": null
        }
      },
      "required": [
        "uriPath",
        "labelAllLocales"
      ]
    },
    "cspDirective": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "properties": {
    "id": {
      "description": "The ID of the Custom Application (when you register the application in the Merchant Center)",
      "type": "string"
    },
    "name": {
      "description": "The name of the Custom Application",
      "type": "string"
    },
    "entryPointUriPath": {
      "description": "The unique route path of the Custom Application. This is the identifier that the Merchant Center Proxy uses to match the HTTP request and forward the request to the Custom Application. This value also needs to be used in the application client side routes. The value must be the same as the `navbarMenu.uriPath` value.",
      "type": "string"
    },
    "cloudIdentifier": {
      "description": "The cloud identifier where the Custom Application is running. This value is used to derive the Merchant Center API URL. Alternatively you can use the `mcApiUrl` property.",
      "type": "string",
      "oneOf": [
        {
          "$ref": "#/definitions/environmentVariable"
        },
        {
          "enum": [
            "gcp-au",
            "gcp-eu",
            "gcp-us",
            "aws-fra",
            "aws-ohio"
          ]
        }
      ]
    },
    "mcApiUrl": {
      "description": "The URL of the Merchant Center API. We usually recommend to use the `cloudIdentifier` option to avoid possible typos.",
      "type": "string"
    },
    "env": {
      "description": "This is an object of keys that represent different environments (development and production). The environment used depends on the environment variable MC_APP_ENV. If MC_APP_ENV isn't set then NODE_ENV will be used, if it's not set then it defaults to \"development\"",
      "type": "object",
      "properties": {
        "development": {
          "description": "Configuration for development only",
          "type": "object",
          "properties": {
            "url": {
              "description": "The URL where the Custom Application is hosted",
              "type": "string"
            },
            "additionalEnvironment": {
              "description": "Additional environment values that are injected in the application context",
              "type": "object"
            },
            "navbarMenu": {
              "description": "Configuration for the menu links for local development. On production the links are configured via the UI when registering the application.",
              "type": "object",
              "allOf": [
                {
                  "$ref": "#/definitions/menuLink"
                },
                {
                  "properties": {
                    "icon": {
                      "description": "The identifier of one of the supported icons",
                      "type": "string",
                      "enum": [
                        "HeartIcon",
                        "PaperclipIcon",
                        "PluginIcon",
                        "RocketIcon",
                        "StarIcon",
                        "ConnectedSquareIcon",
                        "WorldIcon"
                      ]
                    },
                    "submenu": {
                      "description": "A list of sub links",
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/menuLink"
                      },
                      "default": []
                    }
                  },
                  "required": [
                    "icon"
                  ]
                }
              ]
            }
          },
          "required": [
            "url",
            "navbarMenu"
          ]
        },
        "production": {
          "description": "Configuration for development only",
          "type": "object",
          "properties": {
            "url": {
              "description": "The URL where the Custom Application is hosted",
              "type": "string"
            },
            "cdnUrl": {
              "description": "The URL where the Custom Application static assets are hosted, like an external CDN. If the static assets are hosted alongside the Custom Application, you can omit this option and the Custom Application URL will be used instead.",
              "type": "string"
            },
            "additionalEnvironment": {
              "description": "Additional environment values that are injected in the application context",
              "type": "object"
            }
          },
          "required": [
            "url"
          ]
        }
      },
      "required": [
        "development",
        "production"
      ]
    },
    "headers": {
      "description": "Configuration for HTTP headers",
      "type": "object",
      "properties": {
        "csp": {
          "description": "Configuration for the HTTP Content-Security-Policy header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy)",
          "type": "object",
          "properties": {
            "connect-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "font-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "img-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "script-src": {
              "$ref": "#/definitions/cspDirective"
            },
            "style-src": {
              "$ref": "#/definitions/cspDirective"
            }
          },
          "required": [
            "connect-src"
          ]
        },
        "featurePolicies": {
          "description": "Configuration for the HTTP Feature-Policy header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy)",
          "type": "object"
        }
      },
      "required": [
        "csp"
      ]
    }
  },
  "oneOf": [
    {
      "required": [
        "cloudIdentifier"
      ]
    },
    {
      "required": [
        "mcApiUrl"
      ]
    }
  ],
  "required": [
    "name",
    "entryPointUriPath"
  ]
}

=== commercetools/merchant-center-application-kit/packages/application-config/test/fixtures/config-env-variables.json
{
  "name": "avengers-app",
  "entryPointUriPath": "avengers",
  "cloudIdentifier": "${env:CLOUD_IDENTIFIER}",
  "env": {
    "development": {
      "url": "http://localhost:3001",
      "navbarMenu": {
        "uriPath": "avengers",
        "labelAllLocales": [
          {
            "locale": "en",
            "value": "Avengers"
          },
          {
            "locale": "de",
            "value": "Avengers"
          }
        ],
        "icon": "WorldIcon"
      }
    },
    "production": {
      "url": "${env:APP_URL}"
    }
  }
}

=== commercetools/merchant-center-application-kit/packages/application-config/test/fixtures/config-full.json
{
  "name": "avengers-app",
  "cloudIdentifier": "gcp-eu",
  "entryPointUriPath": "avengers",
  "env": {
    "development": {
      "url": "http://localhost:3001",
      "additionalEnvironment": {
        "numberOfMovies": 4
      },
      "navbarMenu": {
        "uriPath": "avengers",
        "labelAllLocales": [
          {
            "locale": "en",
            "value": "Avengers"
          },
          {
            "locale": "de",
            "value": "Avengers"
          }
        ],
        "icon": "WorldIcon",
        "permissions": [
          "ManageProjectSettings"
        ],
        "submenu": [
          {
            "uriPath": "avengers/new",
            "labelAllLocales": [
              {
                "locale": "en",
                "value": "New Avenger"
              },
              {
                "locale": "de",
                "value": "Neu Avenger"
              }
            ],
            "permissions": [
              "ManageProjectSettings"
            ]
          },
          {
            "uriPath": "avengers/members",
            "labelAllLocales": [
              {
                "locale": "en",
                "value": "Avenger members"
              },
              {
                "locale": "de",
                "value": "Avenger Mitglieder"
              }
            ],
            "permissions": [
              "ManageProjectSettings"
            ]
          }
        ]
      }
    },
    "production": {
      "url": "https://avengers.app",
      "cdnUrl": "https://cdn.avengers.app",
      "additionalEnvironment": {
        "numberOfMovies": 4
      }
    }
  },
  "headers": {
    "csp": {
      "script-src": [
        "cdn.avengers.app"
      ],
      "connect-src": [
        "cdn.avengers.app"
      ],
      "style-src": [
        "cdn.avengers.app"
      ]
    },
    "featurePolicies": {
      "microphone": "none"
    }
  }
}
